### ISSUE TITLE
rewrite and debug

### ISSUE THREAD

**Issue by zheoreh** [GitHub30/Apache2.2-PHP5.2.17#1]
Hi @GitHub30. Can you explain please how to enable rewrite module and configure IDE to start debug?

As I understand rewrite module is already enabled and I should configure AllowOverride i.e. link (docker link) httpd.conf and change it to "All".

About debug. I use PHPStorm. I created php server with localhost, port, xdebug and path mapping. I add breakpoints, start listening and open an interesting page but it doesn't work. I also mapped 9000 port for the docker container. But It also doesn't work.

```docker run --name php-academic-2 -v /Users/genius/Desktop/vhosts/academic.expertnegotiator.com/htdocs:/usr/local/apache2/htdocs/ -p 8080:80 -p9000:9000 --link mysql:mysql -d nyanpass/apache2.2-php5.2.17```

<img width="1010" alt="2018-10-30 16 34 59" src="https://user-images.githubusercontent.com/8188225/47721719-cb90c100-dc61-11e8-8e3f-ca23f56c0139.png">

**Comment by zheoreh** [comment]
First question is done. I've installed nano editor in the container and changed the directory option.

**Comment by zheoreh** [comment]
I try next but I cannot still get it work. 

<img width="1021" alt="2018-10-30 18 31 02" src="https://user-images.githubusercontent.com/8188225/47730160-aeb0b980-dc72-11e8-8fef-152ec956bcbc.png">
<img width="1094" alt="2018-10-30 18 31 21" src="https://user-images.githubusercontent.com/8188225/47730161-aeb0b980-dc72-11e8-91ee-7ce4ce8a981b.png">
<img width="341" alt="2018-10-30 18 35 44" src="https://user-images.githubusercontent.com/8188225/47730162-af495000-dc72-11e8-959b-5ed27b3fa71a.png">
<img width="1211" alt="2018-10-30 18 35 50" src="https://user-images.githubusercontent.com/8188225/47730163-af495000-dc72-11e8-9543-4f6e4db2c063.png">

**Comment by GitHub30** [comment]
Hi @zheoreh . Thank you for posting a issue.

I tried debug my environment. it work.
[![Xdebug with Apache 2.2 and PHP 5.2.17 on docker](https://img.youtube.com/vi/BmJ87t1CflY/0.jpg)](https://www.youtube.com/watch?v=BmJ87t1CflY)
[View on YouTube](https://www.youtube.com/watch?v=BmJ87t1CflY)

![screenshot from 2018-10-31 02-35-43](https://user-images.githubusercontent.com/12811398/47739269-60bea480-dcb8-11e8-93fd-fb0f2afe8254.png)
![screenshot from 2018-10-31 02-36-01](https://user-images.githubusercontent.com/12811398/47739279-64522b80-dcb8-11e8-8d4c-ea66b86f874f.png)

**Comment by zheoreh** [comment]
So why it doesn't work for me. I'm doing same.

**Comment by GitHub30** [comment]
Sorry, I don't know offhand. I don't have Mac. I use Ubuntu 18.10. I think that is probably a problem with the network.(plz try xdebug.remote_host=$(/sbin/ip route|awk '/default/ { print $3 }') in the container???)

**Comment by zheoreh** [comment]
https://youtu.be/pJWsdAquzlc - my test example

I don't have /sbin/ip

```
Geniuss-iMac:~ genius$ /sbin/ifconfig 
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
XHC0: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether e0:d5:5e:83:15:4e 
	inet6 fe80::836:90be:2ef5:56d%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.0.103 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex,flow-control>)
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::b5b4:dead:ffd:68a7%utun0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
en2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether e6:e0:a6:41:ff:0f 
	inet6 fe80::80b:7524:941e:ff60%en2 prefixlen 64 secured scopeid 0x8 
	inet 169.254.3.94 netmask 0xffff0000 broadcast 169.254.255.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
```

**Comment by zheoreh** [comment]
<img width="1167" alt="2018-10-30 22 57 56" src="https://user-images.githubusercontent.com/8188225/47746636-7ec7dd00-dc97-11e8-98bf-b228b916a8c2.png">
<img width="667" alt="2018-10-30 22 59 29" src="https://user-images.githubusercontent.com/8188225/47746637-7ec7dd00-dc97-11e8-9093-577b135ae421.png">

Doesn't work too

**Comment by GitHub30** [comment]
Sorry. Set echo "xdebug.remote_host=192.168.0.1" >> /usr/local/lib/php.ini. 192.168.0.1 is default gateway address.
or
docker run ... -e XDEBUG_CONFIG=remote_host=192.168.0.1
https://medium.com/@yuliakostrikova/configure-remote-debugging-with-xdebug-for-php-docker-container-on-macos-8edbc01dc373

**Comment by zheoreh** [comment]
It works. I copied Docker file, changed some xdebug parameters, built a local image, created local IP alias.

xdebug.remote_connect_back=off
xdebug.remote_host=10.254.254.254

sudo ifconfig lo0 alias 10.254.254.254

sudo curl -o /Library/LaunchDaemons/com.yuklia.docker_localhost_alias.plist https://gist.github.com/yuklia/378a7350f8a2456e9513154b962c7cb0

**Comment by GitHub30** [comment]
Great🎉 Thank you for posting a solution.
